apiVersion : apps/v1
kind: Deployment
metadata:
  name: order-service-app
spec:
  selector:
    matchLabels: 
      app: order-service-app
  template:
    metadata:
      labels:
        app: order-service-app
    spec: 
      containers:
      - name: order-service-app
        image: nhlinh2207/orderservice:1
        ports:
        - containerPort: 8082
        env:
          - name: EUREKA_SERVER_ADDRESS
            valueFrom:
              configMapKeyRef:
                key: eureka-service-address
                name: eureka-cm
          - name: CONFIG_SERVER_URL
            valueFrom:
              configMapKeyRef:
                key: config-url
                name: config-cm
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                key: hostname
                name: mysql-cm
          - name: KEYCLOAK_REAML_URL
            valueFrom:
              configMapKeyRef:
                key: keycloak-realm-url
                name: keycloak-cm
---

apiVersion: v1
kind: Service
metadata: 
  name: order-service-svc
spec:
  selector:
    app: order-service-app
  ports:
  - port: 80
    targetPort: 8082