server:
   port: 8088

spring:
   datasource:
      url: ${DB_URL:jdbc:mysql://localhost:3306/microProduct}
      username: ${DB_USER:root}
      password: ${DB_PASS:fireice22072001}
      driverClassname: com.mysql.cj.jdbc.Driver
   jpa:
      database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
      hibernate:
         ddl-auto: update
   application:
      name: PRODUCT-SERVICE
   config:
      import: configserver:${CONFIG_SERVER_URL:http://localhost:9296} # Ket noi Config Server

   security:
      oauth2:
         resourceserver:
            jwt:
               jwk-set-uri: ${KEYCLOAK_REAML_URL:http://192.168.25.128:8080/realms/Micro-Realm}/protocol/openid-connect/certs