server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/microUser
    username: ${DB_USER:root}
    password: ${DB_PASS:fireice22072001}
    driverClassname: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: USER-SERVICE
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296} # Ket noi Config Server

keycloak:
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:2eeJe1p3tOHpW2UOr6hVdzeciR7VEEKm}
  auth-server-url: ${KEYCLOAK_URL:http://192.168.25.131:8080/}
  realm: ${KEYCLOAK_REALM:Micro-Realm}
  resource: ${KEYCLOAK_CLIENT_ID:Micro-Client-Id}
  public-client: true
  bearer-only: true
  cors: true