server:
  port: 8083

spring:
  kafka:
    bootstrap-servers: 192.168.25.128:9092
    consumer:
      group-id: stock
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring:
          json:
            use:
              type:
                headers: false  # not use type in header to deserialize payload
            value:
              default:
                type: com.linh.StockService.model.OrderEvent  # Use this class to deserialize Payload

    topic:
      name: order_topic

